### PR TITLE
[FIX] Yoav removed bootstrap and fixed course remover x

### LINKED ISSUE #57: Reshape and change the color of the 'X' icon in the remove courses feature
## What?

Reshape and change the color of the 'X' icon in the remove courses feature.

Screen Shot 2021-06-18 at 19 11 21

## Why?

To make it more user friendly and to make it compatible with dark-mode.

### LINKED ISSUE #133: Remove the usage of bootstrap
## What?

Remove the usage of Bootstrap.

## Why?

Not be dependent on an external library will increase our security,
And also BootStrap changes some of the styles in the moodles page that we don't like.

### PR DESCRIPTION
**Pull request by norbit8**
## Fixed the following issues:

#133 
#57 

## Main changes:

- Removed the usage of Bootstrap entirely from our project.
- Style changes in the course remover option.

## New Look without dark-mode:

Screen Shot 2021-06-26 at 0 29 28

## New Look in dark-mode:

Screen Shot 2021-06-26 at 0 29 10

### CODE REVIEW

**Comment by idan2468** [comment]
Have you seen how it look like with dark mode and enhance page after removing bootstrap? @norbit8 

Also could you post pic of how the X button looks like now? 
And if working well with the dark mode?

**Comment by norbit8** [comment]
> Have you seen how it look like with dark mode and enhance page after removing bootstrap? @norbit8
> 
> Also could you post pic of how the X button looks like now?
> And if working well with the dark mode?

Updated the first comment, I think it looks legit 😃

**Comment by idan2468** [comment]
> > Have you seen how it look like with dark mode and enhance page after removing bootstrap? @norbit8
> > 
> > Also could you post pic of how the X button looks like now?
> > And if working well with the dark mode?
> 
> Updated the first comment, I think it looks legit 😃 

I like the red color. 
I have 2 improvements that I think could be good if it's possible: 
- Could you add some hover effect to the X button? 
- Is it possible to put the X with the course link at the same "line" (now the X is a little bit upper than the link) 
Maybe we could put the x button after the link and it will look better? 

If it could be done rapidly I think it worth it. 
If no we can put issues for some enhancements for future tasks

What do you think?

**Comment by norbit8** [comment]
> > > Have you seen how it look like with dark mode and enhance page after removing bootstrap? @norbit8
> > > Also could you post pic of how the X button looks like now?
> > > And if working well with the dark mode?
> > 
> > 
> > Updated the first comment, I think it looks legit 😃
> 
> I like the red color.
> I have 2 improvements that I think could be good if it's possible:
> 
> * Could you add some hover effect to the X button?
> * Is it possible to put the X with the course link at the same "line" (now the X is a little bit upper than the link)
>   Maybe we could put the x button after the link and it will look better?
> 
> If it could be done rapidly I think it worth it.
> If no we can put issues for some enhancements for future tasks
> 
> What do you think?

Pushed a new version, I've added the on-over effect.
Changing the `x` to be inline is a bit more complex for me 😆 .
(See the new results on the first PR comment)

**Comment by idan2468** [comment]
> > > > Have you seen how it look like with dark mode and enhance page after removing bootstrap? @norbit8
> > > > Also could you post pic of how the X button looks like now?
> > > > And if working well with the dark mode?
> > > 
> > > 
> > > Updated the first comment, I think it looks legit 😃
> > 
> > I like the red color.
> > I have 2 improvements that I think could be good if it's possible:
> > 
> > * Could you add some hover effect to the X button?
> > * Is it possible to put the X with the course link at the same "line" (now the X is a little bit upper than the link)
> >   Maybe we could put the x button after the link and it will look better?
> > 
> > If it could be done rapidly I think it worth it.
> > If no we can put issues for some enhancements for future tasks
> > 
> > What do you think?
> 
> Pushed a new version, I've added the on-over effect.
> Changing the `x` to be inline is a bit more complex for me 😆 .
> (See the new results on the first PR comment)

Great tnx

**Review by idan2468 — APPROVED** [review]

**Pull request merged**
