### PR TITLE
IdanS pull request first scratch of dark mode

### PR DESCRIPTION
**Pull request by idan2468**

### CODE REVIEW

**Comment by norbit8** [comment]
Great job dude!

Just a few points:
- The injection of the Bootstrap library happens on the manifest.json file, and I totally agree with your comment I'll fix it.
- What do you think about toning down (color-wise) the Moodle's logo and the University logo?
image
- Maybe we should change the colors of the text as well? (It's white right now)

I'll merge this anyways, thanks a-lot :)

**Comment by idan2468** [comment]
> Great job dude!
> 
> Just a few points:
> - The injection of the Bootstrap library happens on the manifest.json file, and I totally agree with your comment I'll fix it.
> - What do you think about toning down (color-wise) the Moodle's logo and the University logo?
> image
> - Maybe we should change the colors of the text as well? (It's white right now)
> 
> I'll merge this anyways, thanks a-lot :)
> 

For now it's just a first scratch, for the logo I can take it to photoshop ans change the color so we can change the logo image. 
What do you think?

**Comment by norbit8** [comment]
Sounds good

**Comment by norbit8** [comment]
@all-contributors please add @idan2468 for infrastructure and code.

**Pull request merged**
